services:
  lsmfapi:
    build: .
    image: lsmfapi:dev
    volumes:
      - ./src:/app/src:ro,z
      - ./static:/app/static:ro,z
      - ./data:/app/data
    environment:
      - PYTHONPYCACHEPREFIX=/tmp/pycache
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lsmfapi-dev.rule=Host(`lsmfapi-dev.lg4.ch`)"
      - "traefik.http.routers.lsmfapi-dev.entrypoints=websecure"
      - "traefik.http.routers.lsmfapi-dev.tls=true"
      - "traefik.http.routers.lsmfapi-dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lsmfapi-dev.service=lsmfapi-dev"
      - "traefik.http.services.lsmfapi-dev.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
